language: java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

branches:
  only:
    - master

script:
  - ./gradlew -Dspring.datasource.username=travis -Dspring.datasource.password= clean build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - mysql