language: java

jdk:
  - oraclejdk8

os:
  - linux

sudo: false

branches:
  only:
    - master

script:
  - ./gradlew --info -Dspring.datasource.url=jdbc:mysql://127.0.0.1:3306/heatmapdb?createDatabaseIfNotExist=true -Dspring.datasource.username=root -Dspring.datasource.password= clean build

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

services:
  - mysql